// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sgarlick987/godivvycloud/client/add_cloud_account"
	"github.com/sgarlick987/godivvycloud/client/clouds"
	"github.com/sgarlick987/godivvycloud/client/organizations"
	"github.com/sgarlick987/godivvycloud/client/resources"
	"github.com/sgarlick987/godivvycloud/client/users"
)

// Default divvy cloud v2 HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "example.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new divvy cloud v2 HTTP client.
func NewHTTPClient(formats strfmt.Registry) *DivvyCloudV2 {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new divvy cloud v2 HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *DivvyCloudV2 {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new divvy cloud v2 client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *DivvyCloudV2 {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(DivvyCloudV2)
	cli.Transport = transport

	cli.AddCloudAccount = add_cloud_account.New(transport, formats)

	cli.Clouds = clouds.New(transport, formats)

	cli.Organizations = organizations.New(transport, formats)

	cli.Resources = resources.New(transport, formats)

	cli.Users = users.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// DivvyCloudV2 is a client for divvy cloud v2
type DivvyCloudV2 struct {
	AddCloudAccount *add_cloud_account.Client

	Clouds *clouds.Client

	Organizations *organizations.Client

	Resources *resources.Client

	Users *users.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *DivvyCloudV2) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.AddCloudAccount.SetTransport(transport)

	c.Clouds.SetTransport(transport)

	c.Organizations.SetTransport(transport)

	c.Resources.SetTransport(transport)

	c.Users.SetTransport(transport)

}
