// Code generated by go-swagger; DO NOT EDIT.

package add_cloud_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new add cloud account API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for add cloud account API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PrototypeCloudAddPost adds AWS cloud account

Adding an AWS cloud account to DivvyCloud using AWS access key and AWS secret key.
*/
func (a *Client) PrototypeCloudAddPost(params *PrototypeCloudAddPostParams) (*PrototypeCloudAddPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPrototypeCloudAddPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PrototypeCloudAddPost",
		Method:             "POST",
		PathPattern:        "/prototype/cloud/add",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PrototypeCloudAddPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PrototypeCloudAddPostOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
