// Code generated by go-swagger; DO NOT EDIT.

package add_cloud_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPrototypeCloudAddPostParams creates a new PrototypeCloudAddPostParams object
// with the default values initialized.
func NewPrototypeCloudAddPostParams() *PrototypeCloudAddPostParams {
	var ()
	return &PrototypeCloudAddPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPrototypeCloudAddPostParamsWithTimeout creates a new PrototypeCloudAddPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPrototypeCloudAddPostParamsWithTimeout(timeout time.Duration) *PrototypeCloudAddPostParams {
	var ()
	return &PrototypeCloudAddPostParams{

		timeout: timeout,
	}
}

// NewPrototypeCloudAddPostParamsWithContext creates a new PrototypeCloudAddPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPrototypeCloudAddPostParamsWithContext(ctx context.Context) *PrototypeCloudAddPostParams {
	var ()
	return &PrototypeCloudAddPostParams{

		Context: ctx,
	}
}

// NewPrototypeCloudAddPostParamsWithHTTPClient creates a new PrototypeCloudAddPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPrototypeCloudAddPostParamsWithHTTPClient(client *http.Client) *PrototypeCloudAddPostParams {
	var ()
	return &PrototypeCloudAddPostParams{
		HTTPClient: client,
	}
}

/*PrototypeCloudAddPostParams contains all the parameters to send to the API endpoint
for the prototype cloud add post operation typically these are written to a http.Request
*/
type PrototypeCloudAddPostParams struct {

	/*Body*/
	Body *models.AddAWSCloudAccountInstanceAssumeRoleRequest
	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) WithTimeout(timeout time.Duration) *PrototypeCloudAddPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) WithContext(ctx context.Context) *PrototypeCloudAddPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) WithHTTPClient(client *http.Client) *PrototypeCloudAddPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) WithBody(body *models.AddAWSCloudAccountInstanceAssumeRoleRequest) *PrototypeCloudAddPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) SetBody(body *models.AddAWSCloudAccountInstanceAssumeRoleRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) WithContentType(contentType string) *PrototypeCloudAddPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) WithXAuthToken(xAuthToken string) *PrototypeCloudAddPostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the prototype cloud add post params
func (o *PrototypeCloudAddPostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PrototypeCloudAddPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
