// Code generated by go-swagger; DO NOT EDIT.

package add_cloud_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// PrototypeCloudAddPostReader is a Reader for the PrototypeCloudAddPost structure.
type PrototypeCloudAddPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PrototypeCloudAddPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPrototypeCloudAddPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPrototypeCloudAddPostOK creates a PrototypeCloudAddPostOK with default headers values
func NewPrototypeCloudAddPostOK() *PrototypeCloudAddPostOK {
	return &PrototypeCloudAddPostOK{
		AccessControlAllowHeaders: "Origin, X-Requested-With, Content-Type, Accept",
		AccessControlAllowMethods: "POST, GET, OPTIONS",
		AccessControlAllowOrigin:  "*",
		ContentLength:             "234",
		Date:                      "Wed, 25 Oct 2017 19:03:45 GMT",
		Server:                    "waitress",
	}
}

/*PrototypeCloudAddPostOK handles this case with default header values.

PrototypeCloudAddPostOK prototype cloud add post o k
*/
type PrototypeCloudAddPostOK struct {
	AccessControlAllowHeaders string

	AccessControlAllowMethods string

	AccessControlAllowOrigin string

	ContentLength string

	Date string

	Server string

	Payload *models.AddAWSCloudAccount
}

func (o *PrototypeCloudAddPostOK) Error() string {
	return fmt.Sprintf("[POST /prototype/cloud/add][%d] prototypeCloudAddPostOK  %+v", 200, o.Payload)
}

func (o *PrototypeCloudAddPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Headers
	o.AccessControlAllowHeaders = response.GetHeader("Access-Control-Allow-Headers")

	// response header Access-Control-Allow-Methods
	o.AccessControlAllowMethods = response.GetHeader("Access-Control-Allow-Methods")

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	// response header Content-Length
	o.ContentLength = response.GetHeader("Content-Length")

	// response header Date
	o.Date = response.GetHeader("Date")

	// response header Server
	o.Server = response.GetHeader("Server")

	o.Payload = new(models.AddAWSCloudAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
