// Code generated by go-swagger; DO NOT EDIT.

package clouds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PrototypeCloudUpdateByCloudIDPostReader is a Reader for the PrototypeCloudUpdateByCloudIDPost structure.
type PrototypeCloudUpdateByCloudIDPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PrototypeCloudUpdateByCloudIDPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPrototypeCloudUpdateByCloudIDPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPrototypeCloudUpdateByCloudIDPostCreated creates a PrototypeCloudUpdateByCloudIDPostCreated with default headers values
func NewPrototypeCloudUpdateByCloudIDPostCreated() *PrototypeCloudUpdateByCloudIDPostCreated {
	return &PrototypeCloudUpdateByCloudIDPostCreated{}
}

/*PrototypeCloudUpdateByCloudIDPostCreated handles this case with default header values.

PrototypeCloudUpdateByCloudIDPostCreated prototype cloud update by cloud Id post created
*/
type PrototypeCloudUpdateByCloudIDPostCreated struct {
}

func (o *PrototypeCloudUpdateByCloudIDPostCreated) Error() string {
	return fmt.Sprintf("[POST /prototype/cloud/{cloud_id}/update][%d] prototypeCloudUpdateByCloudIdPostCreated ", 201)
}

func (o *PrototypeCloudUpdateByCloudIDPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
