// Code generated by go-swagger; DO NOT EDIT.

package clouds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPrototypeCloudUpdateByCloudIDPostParams creates a new PrototypeCloudUpdateByCloudIDPostParams object
// with the default values initialized.
func NewPrototypeCloudUpdateByCloudIDPostParams() *PrototypeCloudUpdateByCloudIDPostParams {
	var ()
	return &PrototypeCloudUpdateByCloudIDPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPrototypeCloudUpdateByCloudIDPostParamsWithTimeout creates a new PrototypeCloudUpdateByCloudIDPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPrototypeCloudUpdateByCloudIDPostParamsWithTimeout(timeout time.Duration) *PrototypeCloudUpdateByCloudIDPostParams {
	var ()
	return &PrototypeCloudUpdateByCloudIDPostParams{

		timeout: timeout,
	}
}

// NewPrototypeCloudUpdateByCloudIDPostParamsWithContext creates a new PrototypeCloudUpdateByCloudIDPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPrototypeCloudUpdateByCloudIDPostParamsWithContext(ctx context.Context) *PrototypeCloudUpdateByCloudIDPostParams {
	var ()
	return &PrototypeCloudUpdateByCloudIDPostParams{

		Context: ctx,
	}
}

// NewPrototypeCloudUpdateByCloudIDPostParamsWithHTTPClient creates a new PrototypeCloudUpdateByCloudIDPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPrototypeCloudUpdateByCloudIDPostParamsWithHTTPClient(client *http.Client) *PrototypeCloudUpdateByCloudIDPostParams {
	var ()
	return &PrototypeCloudUpdateByCloudIDPostParams{
		HTTPClient: client,
	}
}

/*PrototypeCloudUpdateByCloudIDPostParams contains all the parameters to send to the API endpoint
for the prototype cloud update by cloud Id post operation typically these are written to a http.Request
*/
type PrototypeCloudUpdateByCloudIDPostParams struct {

	/*Body*/
	Body *models.CreationParams1
	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string
	/*CloudID*/
	CloudID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithTimeout(timeout time.Duration) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithContext(ctx context.Context) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithHTTPClient(client *http.Client) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithBody(body *models.CreationParams1) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetBody(body *models.CreationParams1) {
	o.Body = body
}

// WithContentType adds the contentType to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithContentType(contentType string) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithXAuthToken(xAuthToken string) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithCloudID adds the cloudID to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) WithCloudID(cloudID int64) *PrototypeCloudUpdateByCloudIDPostParams {
	o.SetCloudID(cloudID)
	return o
}

// SetCloudID adds the cloudId to the prototype cloud update by cloud Id post params
func (o *PrototypeCloudUpdateByCloudIDPostParams) SetCloudID(cloudID int64) {
	o.CloudID = cloudID
}

// WriteToRequest writes these params to a swagger request
func (o *PrototypeCloudUpdateByCloudIDPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param cloud_id
	if err := r.SetPathParam("cloud_id", swag.FormatInt64(o.CloudID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
