// Code generated by go-swagger; DO NOT EDIT.

package clouds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPublicCloudDeleteByCloudResourceIDPostParams creates a new PublicCloudDeleteByCloudResourceIDPostParams object
// with the default values initialized.
func NewPublicCloudDeleteByCloudResourceIDPostParams() *PublicCloudDeleteByCloudResourceIDPostParams {
	var ()
	return &PublicCloudDeleteByCloudResourceIDPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicCloudDeleteByCloudResourceIDPostParamsWithTimeout creates a new PublicCloudDeleteByCloudResourceIDPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicCloudDeleteByCloudResourceIDPostParamsWithTimeout(timeout time.Duration) *PublicCloudDeleteByCloudResourceIDPostParams {
	var ()
	return &PublicCloudDeleteByCloudResourceIDPostParams{

		timeout: timeout,
	}
}

// NewPublicCloudDeleteByCloudResourceIDPostParamsWithContext creates a new PublicCloudDeleteByCloudResourceIDPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicCloudDeleteByCloudResourceIDPostParamsWithContext(ctx context.Context) *PublicCloudDeleteByCloudResourceIDPostParams {
	var ()
	return &PublicCloudDeleteByCloudResourceIDPostParams{

		Context: ctx,
	}
}

// NewPublicCloudDeleteByCloudResourceIDPostParamsWithHTTPClient creates a new PublicCloudDeleteByCloudResourceIDPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicCloudDeleteByCloudResourceIDPostParamsWithHTTPClient(client *http.Client) *PublicCloudDeleteByCloudResourceIDPostParams {
	var ()
	return &PublicCloudDeleteByCloudResourceIDPostParams{
		HTTPClient: client,
	}
}

/*PublicCloudDeleteByCloudResourceIDPostParams contains all the parameters to send to the API endpoint
for the public cloud delete by cloud resource Id post operation typically these are written to a http.Request
*/
type PublicCloudDeleteByCloudResourceIDPostParams struct {

	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string
	/*CloudResourceID*/
	CloudResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WithTimeout(timeout time.Duration) *PublicCloudDeleteByCloudResourceIDPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WithContext(ctx context.Context) *PublicCloudDeleteByCloudResourceIDPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WithHTTPClient(client *http.Client) *PublicCloudDeleteByCloudResourceIDPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WithContentType(contentType string) *PublicCloudDeleteByCloudResourceIDPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WithXAuthToken(xAuthToken string) *PublicCloudDeleteByCloudResourceIDPostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithCloudResourceID adds the cloudResourceID to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WithCloudResourceID(cloudResourceID string) *PublicCloudDeleteByCloudResourceIDPostParams {
	o.SetCloudResourceID(cloudResourceID)
	return o
}

// SetCloudResourceID adds the cloudResourceId to the public cloud delete by cloud resource Id post params
func (o *PublicCloudDeleteByCloudResourceIDPostParams) SetCloudResourceID(cloudResourceID string) {
	o.CloudResourceID = cloudResourceID
}

// WriteToRequest writes these params to a swagger request
func (o *PublicCloudDeleteByCloudResourceIDPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param cloud_resource_id
	if err := r.SetPathParam("cloud_resource_id", o.CloudResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
