// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams creates a new PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams object
// with the default values initialized.
func NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams() *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	var ()
	return &PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParamsWithTimeout creates a new PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParamsWithTimeout(timeout time.Duration) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	var ()
	return &PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams{

		timeout: timeout,
	}
}

// NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParamsWithContext creates a new PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParamsWithContext(ctx context.Context) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	var ()
	return &PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams{

		Context: ctx,
	}
}

// NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParamsWithHTTPClient creates a new PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParamsWithHTTPClient(client *http.Client) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	var ()
	return &PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams{
		HTTPClient: client,
	}
}

/*PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams contains all the parameters to send to the API endpoint
for the prototype domain organization delete by organization resource Id delete operation typically these are written to a http.Request
*/
type PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams struct {

	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string
	/*OrganizationResourceID*/
	OrganizationResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WithTimeout(timeout time.Duration) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WithContext(ctx context.Context) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WithHTTPClient(client *http.Client) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WithContentType(contentType string) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WithXAuthToken(xAuthToken string) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithOrganizationResourceID adds the organizationResourceID to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WithOrganizationResourceID(organizationResourceID string) *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams {
	o.SetOrganizationResourceID(organizationResourceID)
	return o
}

// SetOrganizationResourceID adds the organizationResourceId to the prototype domain organization delete by organization resource Id delete params
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) SetOrganizationResourceID(organizationResourceID string) {
	o.OrganizationResourceID = organizationResourceID
}

// WriteToRequest writes these params to a swagger request
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param organization_resource_id
	if err := r.SetPathParam("organization_resource_id", o.OrganizationResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
