// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPrototypeDomainOrganizationCreatePostParams creates a new PrototypeDomainOrganizationCreatePostParams object
// with the default values initialized.
func NewPrototypeDomainOrganizationCreatePostParams() *PrototypeDomainOrganizationCreatePostParams {
	var ()
	return &PrototypeDomainOrganizationCreatePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPrototypeDomainOrganizationCreatePostParamsWithTimeout creates a new PrototypeDomainOrganizationCreatePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPrototypeDomainOrganizationCreatePostParamsWithTimeout(timeout time.Duration) *PrototypeDomainOrganizationCreatePostParams {
	var ()
	return &PrototypeDomainOrganizationCreatePostParams{

		timeout: timeout,
	}
}

// NewPrototypeDomainOrganizationCreatePostParamsWithContext creates a new PrototypeDomainOrganizationCreatePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPrototypeDomainOrganizationCreatePostParamsWithContext(ctx context.Context) *PrototypeDomainOrganizationCreatePostParams {
	var ()
	return &PrototypeDomainOrganizationCreatePostParams{

		Context: ctx,
	}
}

// NewPrototypeDomainOrganizationCreatePostParamsWithHTTPClient creates a new PrototypeDomainOrganizationCreatePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPrototypeDomainOrganizationCreatePostParamsWithHTTPClient(client *http.Client) *PrototypeDomainOrganizationCreatePostParams {
	var ()
	return &PrototypeDomainOrganizationCreatePostParams{
		HTTPClient: client,
	}
}

/*PrototypeDomainOrganizationCreatePostParams contains all the parameters to send to the API endpoint
for the prototype domain organization create post operation typically these are written to a http.Request
*/
type PrototypeDomainOrganizationCreatePostParams struct {

	/*Body*/
	Body *models.CreateneworganizationRequest
	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) WithTimeout(timeout time.Duration) *PrototypeDomainOrganizationCreatePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) WithContext(ctx context.Context) *PrototypeDomainOrganizationCreatePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) WithHTTPClient(client *http.Client) *PrototypeDomainOrganizationCreatePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) WithBody(body *models.CreateneworganizationRequest) *PrototypeDomainOrganizationCreatePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) SetBody(body *models.CreateneworganizationRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) WithContentType(contentType string) *PrototypeDomainOrganizationCreatePostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) WithXAuthToken(xAuthToken string) *PrototypeDomainOrganizationCreatePostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the prototype domain organization create post params
func (o *PrototypeDomainOrganizationCreatePostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PrototypeDomainOrganizationCreatePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
