// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// PrototypeDomainOrganizationCreatePostReader is a Reader for the PrototypeDomainOrganizationCreatePost structure.
type PrototypeDomainOrganizationCreatePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PrototypeDomainOrganizationCreatePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPrototypeDomainOrganizationCreatePostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPrototypeDomainOrganizationCreatePostOK creates a PrototypeDomainOrganizationCreatePostOK with default headers values
func NewPrototypeDomainOrganizationCreatePostOK() *PrototypeDomainOrganizationCreatePostOK {
	return &PrototypeDomainOrganizationCreatePostOK{}
}

/*PrototypeDomainOrganizationCreatePostOK handles this case with default header values.

PrototypeDomainOrganizationCreatePostOK prototype domain organization create post o k
*/
type PrototypeDomainOrganizationCreatePostOK struct {
	Payload *models.DomainOrganizationCreateResponse
}

func (o *PrototypeDomainOrganizationCreatePostOK) Error() string {
	return fmt.Sprintf("[POST /prototype/domain/organization/create][%d] prototypeDomainOrganizationCreatePostOK  %+v", 200, o.Payload)
}

func (o *PrototypeDomainOrganizationCreatePostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DomainOrganizationCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
