// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteReader is a Reader for the PrototypeDomainOrganizationDeleteByOrganizationResourceIDDelete structure.
type PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK creates a PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK with default headers values
func NewPrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK() *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK {
	return &PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK{}
}

/*PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK handles this case with default header values.

PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK prototype domain organization delete by organization resource Id delete o k
*/
type PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK struct {
}

func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /prototype/domain/organization/{organization_resource_id}/delete][%d] prototypeDomainOrganizationDeleteByOrganizationResourceIdDeleteOK ", 200)
}

func (o *PrototypeDomainOrganizationDeleteByOrganizationResourceIDDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
