// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams creates a new PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams object
// with the default values initialized.
func NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams() *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	var ()
	return &PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParamsWithTimeout creates a new PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParamsWithTimeout(timeout time.Duration) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	var ()
	return &PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams{

		timeout: timeout,
	}
}

// NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParamsWithContext creates a new PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParamsWithContext(ctx context.Context) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	var ()
	return &PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams{

		Context: ctx,
	}
}

// NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParamsWithHTTPClient creates a new PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParamsWithHTTPClient(client *http.Client) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	var ()
	return &PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams{
		HTTPClient: client,
	}
}

/*PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams contains all the parameters to send to the API endpoint
for the prototype domain organization update by organization resource Id post operation typically these are written to a http.Request
*/
type PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams struct {

	/*Body*/
	Body *models.EditorganizationnameRequest
	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string
	/*OrganizationResourceID*/
	OrganizationResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithTimeout(timeout time.Duration) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithContext(ctx context.Context) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithHTTPClient(client *http.Client) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithBody(body *models.EditorganizationnameRequest) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetBody(body *models.EditorganizationnameRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithContentType(contentType string) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithXAuthToken(xAuthToken string) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithOrganizationResourceID adds the organizationResourceID to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WithOrganizationResourceID(organizationResourceID string) *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams {
	o.SetOrganizationResourceID(organizationResourceID)
	return o
}

// SetOrganizationResourceID adds the organizationResourceId to the prototype domain organization update by organization resource Id post params
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) SetOrganizationResourceID(organizationResourceID string) {
	o.OrganizationResourceID = organizationResourceID
}

// WriteToRequest writes these params to a swagger request
func (o *PrototypeDomainOrganizationUpdateByOrganizationResourceIDPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param organization_resource_id
	if err := r.SetPathParam("organization_resource_id", o.OrganizationResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
