// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPublicUserLoginPostParams creates a new PublicUserLoginPostParams object
// with the default values initialized.
func NewPublicUserLoginPostParams() *PublicUserLoginPostParams {
	var ()
	return &PublicUserLoginPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicUserLoginPostParamsWithTimeout creates a new PublicUserLoginPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicUserLoginPostParamsWithTimeout(timeout time.Duration) *PublicUserLoginPostParams {
	var ()
	return &PublicUserLoginPostParams{

		timeout: timeout,
	}
}

// NewPublicUserLoginPostParamsWithContext creates a new PublicUserLoginPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicUserLoginPostParamsWithContext(ctx context.Context) *PublicUserLoginPostParams {
	var ()
	return &PublicUserLoginPostParams{

		Context: ctx,
	}
}

// NewPublicUserLoginPostParamsWithHTTPClient creates a new PublicUserLoginPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicUserLoginPostParamsWithHTTPClient(client *http.Client) *PublicUserLoginPostParams {
	var ()
	return &PublicUserLoginPostParams{
		HTTPClient: client,
	}
}

/*PublicUserLoginPostParams contains all the parameters to send to the API endpoint
for the public user login post operation typically these are written to a http.Request
*/
type PublicUserLoginPostParams struct {

	/*Body*/
	Body *models.LoginRequest
	/*ContentType*/
	ContentType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public user login post params
func (o *PublicUserLoginPostParams) WithTimeout(timeout time.Duration) *PublicUserLoginPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public user login post params
func (o *PublicUserLoginPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public user login post params
func (o *PublicUserLoginPostParams) WithContext(ctx context.Context) *PublicUserLoginPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public user login post params
func (o *PublicUserLoginPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public user login post params
func (o *PublicUserLoginPostParams) WithHTTPClient(client *http.Client) *PublicUserLoginPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public user login post params
func (o *PublicUserLoginPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public user login post params
func (o *PublicUserLoginPostParams) WithBody(body *models.LoginRequest) *PublicUserLoginPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public user login post params
func (o *PublicUserLoginPostParams) SetBody(body *models.LoginRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the public user login post params
func (o *PublicUserLoginPostParams) WithContentType(contentType string) *PublicUserLoginPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public user login post params
func (o *PublicUserLoginPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WriteToRequest writes these params to a swagger request
func (o *PublicUserLoginPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
