// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// PublicUserLoginPostReader is a Reader for the PublicUserLoginPost structure.
type PublicUserLoginPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicUserLoginPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicUserLoginPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicUserLoginPostOK creates a PublicUserLoginPostOK with default headers values
func NewPublicUserLoginPostOK() *PublicUserLoginPostOK {
	return &PublicUserLoginPostOK{
		AccessControlAllowHeaders: "Origin, X-Requested-With, Content-Type, Accept",
		AccessControlAllowMethods: "POST, GET, OPTIONS",
		AccessControlAllowOrigin:  "*",
		ContentLength:             "286",
		Date:                      "Mon, 07 Nov 2016 15:12:28 GMT",
		Server:                    "waitress",
	}
}

/*PublicUserLoginPostOK handles this case with default header values.

PublicUserLoginPostOK public user login post o k
*/
type PublicUserLoginPostOK struct {
	AccessControlAllowHeaders string

	AccessControlAllowMethods string

	AccessControlAllowOrigin string

	ContentLength string

	Date string

	Server string

	Payload *models.OriginalAuth
}

func (o *PublicUserLoginPostOK) Error() string {
	return fmt.Sprintf("[POST /public/user/login][%d] publicUserLoginPostOK  %+v", 200, o.Payload)
}

func (o *PublicUserLoginPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Headers
	o.AccessControlAllowHeaders = response.GetHeader("Access-Control-Allow-Headers")

	// response header Access-Control-Allow-Methods
	o.AccessControlAllowMethods = response.GetHeader("Access-Control-Allow-Methods")

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	// response header Content-Length
	o.ContentLength = response.GetHeader("Content-Length")

	// response header Date
	o.Date = response.GetHeader("Date")

	// response header Server
	o.Server = response.GetHeader("Server")

	o.Payload = new(models.OriginalAuth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
