// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new users API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for users API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PublicUserLoginPost logins

Authenticate User, returns X-Auth-Token
*/
func (a *Client) PublicUserLoginPost(params *PublicUserLoginPostParams) (*PublicUserLoginPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPublicUserLoginPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PublicUserLoginPost",
		Method:             "POST",
		PathPattern:        "/public/user/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PublicUserLoginPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PublicUserLoginPostOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
