// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PublicCloudEventdrivenharvestEnableReader is a Reader for the PublicCloudEventdrivenharvestEnable structure.
type PublicCloudEventdrivenharvestEnableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudEventdrivenharvestEnableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudEventdrivenharvestEnableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudEventdrivenharvestEnableOK creates a PublicCloudEventdrivenharvestEnableOK with default headers values
func NewPublicCloudEventdrivenharvestEnableOK() *PublicCloudEventdrivenharvestEnableOK {
	return &PublicCloudEventdrivenharvestEnableOK{}
}

/*PublicCloudEventdrivenharvestEnableOK handles this case with default header values.

PublicCloudEventdrivenharvestEnableOK public cloud eventdrivenharvest enable o k
*/
type PublicCloudEventdrivenharvestEnableOK struct {
}

func (o *PublicCloudEventdrivenharvestEnableOK) Error() string {
	return fmt.Sprintf("[POST /public/cloud/eventdrivenharvest][%d] publicCloudEventdrivenharvestEnableOK ", 200)
}

func (o *PublicCloudEventdrivenharvestEnableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
