// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPublicCloudEventdrivenharvestByOrganizationidPostParams creates a new PublicCloudEventdrivenharvestByOrganizationidPostParams object
// with the default values initialized.
func NewPublicCloudEventdrivenharvestByOrganizationidPostParams() *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestByOrganizationidPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicCloudEventdrivenharvestByOrganizationidPostParamsWithTimeout creates a new PublicCloudEventdrivenharvestByOrganizationidPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicCloudEventdrivenharvestByOrganizationidPostParamsWithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestByOrganizationidPostParams{

		timeout: timeout,
	}
}

// NewPublicCloudEventdrivenharvestByOrganizationidPostParamsWithContext creates a new PublicCloudEventdrivenharvestByOrganizationidPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicCloudEventdrivenharvestByOrganizationidPostParamsWithContext(ctx context.Context) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestByOrganizationidPostParams{

		Context: ctx,
	}
}

// NewPublicCloudEventdrivenharvestByOrganizationidPostParamsWithHTTPClient creates a new PublicCloudEventdrivenharvestByOrganizationidPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicCloudEventdrivenharvestByOrganizationidPostParamsWithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestByOrganizationidPostParams{
		HTTPClient: client,
	}
}

/*PublicCloudEventdrivenharvestByOrganizationidPostParams contains all the parameters to send to the API endpoint
for the public cloud eventdrivenharvest by organizationid post operation typically these are written to a http.Request
*/
type PublicCloudEventdrivenharvestByOrganizationidPostParams struct {

	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string
	/*Organizationid*/
	Organizationid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WithContext(ctx context.Context) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WithContentType(contentType string) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WithXAuthToken(xAuthToken string) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithOrganizationid adds the organizationid to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WithOrganizationid(organizationid string) *PublicCloudEventdrivenharvestByOrganizationidPostParams {
	o.SetOrganizationid(organizationid)
	return o
}

// SetOrganizationid adds the organizationid to the public cloud eventdrivenharvest by organizationid post params
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) SetOrganizationid(organizationid string) {
	o.Organizationid = organizationid
}

// WriteToRequest writes these params to a swagger request
func (o *PublicCloudEventdrivenharvestByOrganizationidPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param organizationid
	if err := r.SetPathParam("organizationid", o.Organizationid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
