// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// PublicCloudEventdrivenharvestReader is a Reader for the PublicCloudEventdrivenharvest structure.
type PublicCloudEventdrivenharvestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudEventdrivenharvestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudEventdrivenharvestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudEventdrivenharvestOK creates a PublicCloudEventdrivenharvestOK with default headers values
func NewPublicCloudEventdrivenharvestOK() *PublicCloudEventdrivenharvestOK {
	return &PublicCloudEventdrivenharvestOK{}
}

/*PublicCloudEventdrivenharvestOK handles this case with default header values.

PublicCloudEventdrivenharvestOK public cloud eventdrivenharvest o k
*/
type PublicCloudEventdrivenharvestOK struct {
	Payload *models.EventDrivenHarvestingStatus
}

func (o *PublicCloudEventdrivenharvestOK) Error() string {
	return fmt.Sprintf("[GET /public/cloud/eventdrivenharvest][%d] publicCloudEventdrivenharvestOK  %+v", 200, o.Payload)
}

func (o *PublicCloudEventdrivenharvestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventDrivenHarvestingStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
