// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteReader is a Reader for the PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDelete structure.
type PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK creates a PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK with default headers values
func NewPublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK() *PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK {
	return &PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK{}
}

/*PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK handles this case with default header values.

PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK public cloud eventdrivenharvest disable consumer by organizationid delete o k
*/
type PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK struct {
}

func (o *PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /public/cloud/eventdrivenharvest/{organizationid}/disable-consumer][%d] publicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK ", 200)
}

func (o *PublicCloudEventdrivenharvestDisableConsumerByOrganizationidDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
