// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostReader is a Reader for the PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPost structure.
type PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK creates a PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK with default headers values
func NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK() *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK {
	return &PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK{}
}

/*PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK handles this case with default header values.

PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK public cloud eventdrivenharvest consumer producers add by organizationid post o k
*/
type PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK struct {
}

func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK) Error() string {
	return fmt.Sprintf("[POST /public/cloud/eventdrivenharvest/consumer/{organizationid}/producers/add][%d] publicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK ", 200)
}

func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
