// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPublicCloudEventdrivenharvestParams creates a new PublicCloudEventdrivenharvestParams object
// with the default values initialized.
func NewPublicCloudEventdrivenharvestParams() *PublicCloudEventdrivenharvestParams {
	var ()
	return &PublicCloudEventdrivenharvestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicCloudEventdrivenharvestParamsWithTimeout creates a new PublicCloudEventdrivenharvestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicCloudEventdrivenharvestParamsWithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestParams {
	var ()
	return &PublicCloudEventdrivenharvestParams{

		timeout: timeout,
	}
}

// NewPublicCloudEventdrivenharvestParamsWithContext creates a new PublicCloudEventdrivenharvestParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicCloudEventdrivenharvestParamsWithContext(ctx context.Context) *PublicCloudEventdrivenharvestParams {
	var ()
	return &PublicCloudEventdrivenharvestParams{

		Context: ctx,
	}
}

// NewPublicCloudEventdrivenharvestParamsWithHTTPClient creates a new PublicCloudEventdrivenharvestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicCloudEventdrivenharvestParamsWithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestParams {
	var ()
	return &PublicCloudEventdrivenharvestParams{
		HTTPClient: client,
	}
}

/*PublicCloudEventdrivenharvestParams contains all the parameters to send to the API endpoint
for the public cloud eventdrivenharvest operation typically these are written to a http.Request
*/
type PublicCloudEventdrivenharvestParams struct {

	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) WithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) WithContext(ctx context.Context) *PublicCloudEventdrivenharvestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) WithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) WithContentType(contentType string) *PublicCloudEventdrivenharvestParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) WithXAuthToken(xAuthToken string) *PublicCloudEventdrivenharvestParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest params
func (o *PublicCloudEventdrivenharvestParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PublicCloudEventdrivenharvestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
