// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPublicCloudEventdrivenharvestProducersDisablePostParams creates a new PublicCloudEventdrivenharvestProducersDisablePostParams object
// with the default values initialized.
func NewPublicCloudEventdrivenharvestProducersDisablePostParams() *PublicCloudEventdrivenharvestProducersDisablePostParams {
	var ()
	return &PublicCloudEventdrivenharvestProducersDisablePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicCloudEventdrivenharvestProducersDisablePostParamsWithTimeout creates a new PublicCloudEventdrivenharvestProducersDisablePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicCloudEventdrivenharvestProducersDisablePostParamsWithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	var ()
	return &PublicCloudEventdrivenharvestProducersDisablePostParams{

		timeout: timeout,
	}
}

// NewPublicCloudEventdrivenharvestProducersDisablePostParamsWithContext creates a new PublicCloudEventdrivenharvestProducersDisablePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicCloudEventdrivenharvestProducersDisablePostParamsWithContext(ctx context.Context) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	var ()
	return &PublicCloudEventdrivenharvestProducersDisablePostParams{

		Context: ctx,
	}
}

// NewPublicCloudEventdrivenharvestProducersDisablePostParamsWithHTTPClient creates a new PublicCloudEventdrivenharvestProducersDisablePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicCloudEventdrivenharvestProducersDisablePostParamsWithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	var ()
	return &PublicCloudEventdrivenharvestProducersDisablePostParams{
		HTTPClient: client,
	}
}

/*PublicCloudEventdrivenharvestProducersDisablePostParams contains all the parameters to send to the API endpoint
for the public cloud eventdrivenharvest producers disable post operation typically these are written to a http.Request
*/
type PublicCloudEventdrivenharvestProducersDisablePostParams struct {

	/*Body*/
	Body *models.RemoveProducerRequest
	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WithContext(ctx context.Context) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WithBody(body *models.RemoveProducerRequest) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) SetBody(body *models.RemoveProducerRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WithContentType(contentType string) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WithXAuthToken(xAuthToken string) *PublicCloudEventdrivenharvestProducersDisablePostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest producers disable post params
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PublicCloudEventdrivenharvestProducersDisablePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
