// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams creates a new PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams object
// with the default values initialized.
func NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams() *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParamsWithTimeout creates a new PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParamsWithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams{

		timeout: timeout,
	}
}

// NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParamsWithContext creates a new PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParamsWithContext(ctx context.Context) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams{

		Context: ctx,
	}
}

// NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParamsWithHTTPClient creates a new PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParamsWithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	var ()
	return &PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams{
		HTTPClient: client,
	}
}

/*PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams contains all the parameters to send to the API endpoint
for the public cloud eventdrivenharvest consumer producers add by organizationid post operation typically these are written to a http.Request
*/
type PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams struct {

	/*Body*/
	Body *models.AddProducerRequest
	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string
	/*Organizationid*/
	Organizationid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithContext(ctx context.Context) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithBody(body *models.AddProducerRequest) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetBody(body *models.AddProducerRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithContentType(contentType string) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithXAuthToken(xAuthToken string) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithOrganizationid adds the organizationid to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WithOrganizationid(organizationid string) *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams {
	o.SetOrganizationid(organizationid)
	return o
}

// SetOrganizationid adds the organizationid to the public cloud eventdrivenharvest consumer producers add by organizationid post params
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) SetOrganizationid(organizationid string) {
	o.Organizationid = organizationid
}

// WriteToRequest writes these params to a swagger request
func (o *PublicCloudEventdrivenharvestConsumerProducersAddByOrganizationidPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param organizationid
	if err := r.SetPathParam("organizationid", o.Organizationid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
