// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sgarlick987/godivvycloud/models"
)

// PublicCloudConsumersGetReader is a Reader for the PublicCloudConsumersGet structure.
type PublicCloudConsumersGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudConsumersGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudConsumersGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudConsumersGetOK creates a PublicCloudConsumersGetOK with default headers values
func NewPublicCloudConsumersGetOK() *PublicCloudConsumersGetOK {
	return &PublicCloudConsumersGetOK{}
}

/*PublicCloudConsumersGetOK handles this case with default header values.

PublicCloudConsumersGetOK public cloud consumers get o k
*/
type PublicCloudConsumersGetOK struct {
	Payload *models.ListConsumers
}

func (o *PublicCloudConsumersGetOK) Error() string {
	return fmt.Sprintf("[GET /public/cloud/consumers][%d] publicCloudConsumersGetOK  %+v", 200, o.Payload)
}

func (o *PublicCloudConsumersGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListConsumers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
