// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPublicCloudEventdrivenharvestEnableParams creates a new PublicCloudEventdrivenharvestEnableParams object
// with the default values initialized.
func NewPublicCloudEventdrivenharvestEnableParams() *PublicCloudEventdrivenharvestEnableParams {
	var ()
	return &PublicCloudEventdrivenharvestEnableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicCloudEventdrivenharvestEnableParamsWithTimeout creates a new PublicCloudEventdrivenharvestEnableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicCloudEventdrivenharvestEnableParamsWithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestEnableParams {
	var ()
	return &PublicCloudEventdrivenharvestEnableParams{

		timeout: timeout,
	}
}

// NewPublicCloudEventdrivenharvestEnableParamsWithContext creates a new PublicCloudEventdrivenharvestEnableParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicCloudEventdrivenharvestEnableParamsWithContext(ctx context.Context) *PublicCloudEventdrivenharvestEnableParams {
	var ()
	return &PublicCloudEventdrivenharvestEnableParams{

		Context: ctx,
	}
}

// NewPublicCloudEventdrivenharvestEnableParamsWithHTTPClient creates a new PublicCloudEventdrivenharvestEnableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicCloudEventdrivenharvestEnableParamsWithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestEnableParams {
	var ()
	return &PublicCloudEventdrivenharvestEnableParams{
		HTTPClient: client,
	}
}

/*PublicCloudEventdrivenharvestEnableParams contains all the parameters to send to the API endpoint
for the public cloud eventdrivenharvest enable operation typically these are written to a http.Request
*/
type PublicCloudEventdrivenharvestEnableParams struct {

	/*ContentType*/
	ContentType string
	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) WithTimeout(timeout time.Duration) *PublicCloudEventdrivenharvestEnableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) WithContext(ctx context.Context) *PublicCloudEventdrivenharvestEnableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) WithHTTPClient(client *http.Client) *PublicCloudEventdrivenharvestEnableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) WithContentType(contentType string) *PublicCloudEventdrivenharvestEnableParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) WithXAuthToken(xAuthToken string) *PublicCloudEventdrivenharvestEnableParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the public cloud eventdrivenharvest enable params
func (o *PublicCloudEventdrivenharvestEnableParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PublicCloudEventdrivenharvestEnableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
