// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PublicCloudEventdrivenharvestByOrganizationidPostReader is a Reader for the PublicCloudEventdrivenharvestByOrganizationidPost structure.
type PublicCloudEventdrivenharvestByOrganizationidPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudEventdrivenharvestByOrganizationidPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudEventdrivenharvestByOrganizationidPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudEventdrivenharvestByOrganizationidPostOK creates a PublicCloudEventdrivenharvestByOrganizationidPostOK with default headers values
func NewPublicCloudEventdrivenharvestByOrganizationidPostOK() *PublicCloudEventdrivenharvestByOrganizationidPostOK {
	return &PublicCloudEventdrivenharvestByOrganizationidPostOK{}
}

/*PublicCloudEventdrivenharvestByOrganizationidPostOK handles this case with default header values.

PublicCloudEventdrivenharvestByOrganizationidPostOK public cloud eventdrivenharvest by organizationid post o k
*/
type PublicCloudEventdrivenharvestByOrganizationidPostOK struct {
}

func (o *PublicCloudEventdrivenharvestByOrganizationidPostOK) Error() string {
	return fmt.Sprintf("[POST /public/cloud/eventdrivenharvest/{organizationid}][%d] publicCloudEventdrivenharvestByOrganizationidPostOK ", 200)
}

func (o *PublicCloudEventdrivenharvestByOrganizationidPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
