// Code generated by go-swagger; DO NOT EDIT.

package event_driven_harvesting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PublicCloudEventdrivenharvestProducersDisablePostReader is a Reader for the PublicCloudEventdrivenharvestProducersDisablePost structure.
type PublicCloudEventdrivenharvestProducersDisablePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicCloudEventdrivenharvestProducersDisablePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicCloudEventdrivenharvestProducersDisablePostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicCloudEventdrivenharvestProducersDisablePostOK creates a PublicCloudEventdrivenharvestProducersDisablePostOK with default headers values
func NewPublicCloudEventdrivenharvestProducersDisablePostOK() *PublicCloudEventdrivenharvestProducersDisablePostOK {
	return &PublicCloudEventdrivenharvestProducersDisablePostOK{}
}

/*PublicCloudEventdrivenharvestProducersDisablePostOK handles this case with default header values.

PublicCloudEventdrivenharvestProducersDisablePostOK public cloud eventdrivenharvest producers disable post o k
*/
type PublicCloudEventdrivenharvestProducersDisablePostOK struct {
}

func (o *PublicCloudEventdrivenharvestProducersDisablePostOK) Error() string {
	return fmt.Sprintf("[POST /public/cloud/eventdrivenharvest/producers/disable][%d] publicCloudEventdrivenharvestProducersDisablePostOK ", 200)
}

func (o *PublicCloudEventdrivenharvestProducersDisablePostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
