// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Cloud Cloud
// swagger:model Cloud
type Cloud struct {

	// cloud access
	// Required: true
	CloudAccess *string `json:"cloud_access"`

	// cloud type id
	// Required: true
	CloudTypeID *string `json:"cloud_type_id"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this cloud
func (m *Cloud) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCloudAccess(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloudTypeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Cloud) validateCloudAccess(formats strfmt.Registry) error {

	if err := validate.Required("cloud_access", "body", m.CloudAccess); err != nil {
		return err
	}

	return nil
}

func (m *Cloud) validateCloudTypeID(formats strfmt.Registry) error {

	if err := validate.Required("cloud_type_id", "body", m.CloudTypeID); err != nil {
		return err
	}

	return nil
}

func (m *Cloud) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Cloud) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Cloud) UnmarshalBinary(b []byte) error {
	var res Cloud
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
