// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreationParams2 CreationParams2
// swagger:model CreationParams2
type CreationParams2 struct {

	// account number
	// Required: true
	AccountNumber *string `json:"account_number"`

	// api key
	// Required: true
	APIKey *string `json:"api_key"`

	// authentication type
	// Required: true
	AuthenticationType *string `json:"authentication_type"`

	// cloud type
	// Required: true
	CloudType *string `json:"cloud_type"`

	// duration
	// Required: true
	Duration *int32 `json:"duration"`

	// external id
	// Required: true
	ExternalID *string `json:"external_id"`

	// name
	// Required: true
	Name *string `json:"name"`

	// role arn
	// Required: true
	RoleArn *string `json:"role_arn"`

	// secret key
	// Required: true
	SecretKey *string `json:"secret_key"`

	// session name
	// Required: true
	SessionName *string `json:"session_name"`
}

// Validate validates this creation params2
func (m *CreationParams2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthenticationType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloudType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDuration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExternalID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoleArn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecretKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreationParams2) validateAccountNumber(formats strfmt.Registry) error {

	if err := validate.Required("account_number", "body", m.AccountNumber); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateAPIKey(formats strfmt.Registry) error {

	if err := validate.Required("api_key", "body", m.APIKey); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateAuthenticationType(formats strfmt.Registry) error {

	if err := validate.Required("authentication_type", "body", m.AuthenticationType); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateCloudType(formats strfmt.Registry) error {

	if err := validate.Required("cloud_type", "body", m.CloudType); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateDuration(formats strfmt.Registry) error {

	if err := validate.Required("duration", "body", m.Duration); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateExternalID(formats strfmt.Registry) error {

	if err := validate.Required("external_id", "body", m.ExternalID); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateRoleArn(formats strfmt.Registry) error {

	if err := validate.Required("role_arn", "body", m.RoleArn); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateSecretKey(formats strfmt.Registry) error {

	if err := validate.Required("secret_key", "body", m.SecretKey); err != nil {
		return err
	}

	return nil
}

func (m *CreationParams2) validateSessionName(formats strfmt.Registry) error {

	if err := validate.Required("session_name", "body", m.SessionName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreationParams2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreationParams2) UnmarshalBinary(b []byte) error {
	var res CreationParams2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
