// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DomainOrganizationCreateResponse DomainOrganizationCreateResponse
// swagger:model DomainOrganizationCreateResponse
type DomainOrganizationCreateResponse struct {

	// organization id
	OrganizationID int32 `json:"organization_id,omitempty"`

	// resource id
	ResourceID string `json:"resource_id,omitempty"`
}

// Validate validates this domain organization create response
func (m *DomainOrganizationCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DomainOrganizationCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainOrganizationCreateResponse) UnmarshalBinary(b []byte) error {
	var res DomainOrganizationCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
