// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EditorganizationnameRequest EditorganizationnameRequest
// swagger:model EditorganizationnameRequest
type EditorganizationnameRequest struct {

	// organization name
	// Required: true
	OrganizationName *string `json:"organization_name"`
}

// Validate validates this editorganizationname request
func (m *EditorganizationnameRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrganizationName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EditorganizationnameRequest) validateOrganizationName(formats strfmt.Registry) error {

	if err := validate.Required("organization_name", "body", m.OrganizationName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EditorganizationnameRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditorganizationnameRequest) UnmarshalBinary(b []byte) error {
	var res EditorganizationnameRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
