// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventDrivenHarvestingStatus EventDrivenHarvestingStatus
// swagger:model EventDrivenHarvestingStatus
type EventDrivenHarvestingStatus struct {

	// event driven harvest enabled
	// Required: true
	EventDrivenHarvestEnabled *bool `json:"event_driven_harvest_enabled"`
}

// Validate validates this event driven harvesting status
func (m *EventDrivenHarvestingStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventDrivenHarvestEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventDrivenHarvestingStatus) validateEventDrivenHarvestEnabled(formats strfmt.Registry) error {

	if err := validate.Required("event_driven_harvest_enabled", "body", m.EventDrivenHarvestEnabled); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventDrivenHarvestingStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventDrivenHarvestingStatus) UnmarshalBinary(b []byte) error {
	var res EventDrivenHarvestingStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
