// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListCloudTypes ListCloudTypes
// swagger:model ListCloudTypes
type ListCloudTypes struct {

	// clouds
	// Required: true
	Clouds []*Cloud `json:"clouds"`
}

// Validate validates this list cloud types
func (m *ListCloudTypes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClouds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListCloudTypes) validateClouds(formats strfmt.Registry) error {

	if err := validate.Required("clouds", "body", m.Clouds); err != nil {
		return err
	}

	for i := 0; i < len(m.Clouds); i++ {
		if swag.IsZero(m.Clouds[i]) { // not required
			continue
		}

		if m.Clouds[i] != nil {
			if err := m.Clouds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clouds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListCloudTypes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListCloudTypes) UnmarshalBinary(b []byte) error {
	var res ListCloudTypes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
