// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListConsumers ListConsumers
// swagger:model ListConsumers
type ListConsumers struct {

	// consumers
	// Required: true
	Consumers []*Consumer `json:"consumers"`
}

// Validate validates this list consumers
func (m *ListConsumers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsumers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListConsumers) validateConsumers(formats strfmt.Registry) error {

	if err := validate.Required("consumers", "body", m.Consumers); err != nil {
		return err
	}

	for i := 0; i < len(m.Consumers); i++ {
		if swag.IsZero(m.Consumers[i]) { // not required
			continue
		}

		if m.Consumers[i] != nil {
			if err := m.Consumers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("consumers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListConsumers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListConsumers) UnmarshalBinary(b []byte) error {
	var res ListConsumers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
