// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Noncompliance Noncompliance
// swagger:model Noncompliance
type Noncompliance struct {

	// reporter resource id
	// Required: true
	ReporterResourceID *string `json:"reporter_resource_id"`

	// resource id
	// Required: true
	ResourceID *string `json:"resource_id"`
}

// Validate validates this noncompliance
func (m *Noncompliance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReporterResourceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Noncompliance) validateReporterResourceID(formats strfmt.Registry) error {

	if err := validate.Required("reporter_resource_id", "body", m.ReporterResourceID); err != nil {
		return err
	}

	return nil
}

func (m *Noncompliance) validateResourceID(formats strfmt.Registry) error {

	if err := validate.Required("resource_id", "body", m.ResourceID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Noncompliance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Noncompliance) UnmarshalBinary(b []byte) error {
	var res Noncompliance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
