// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Propagate Propagate
// swagger:model Propagate
type Propagate struct {

	// badges
	// Required: true
	Badges []string `json:"badges"`

	// by badge
	// Required: true
	ByBadge *bool `json:"by_badge"`

	// by consumer
	// Required: true
	ByConsumer *bool `json:"by_consumer"`
}

// Validate validates this propagate
func (m *Propagate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBadges(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateByBadge(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateByConsumer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Propagate) validateBadges(formats strfmt.Registry) error {

	if err := validate.Required("badges", "body", m.Badges); err != nil {
		return err
	}

	return nil
}

func (m *Propagate) validateByBadge(formats strfmt.Registry) error {

	if err := validate.Required("by_badge", "body", m.ByBadge); err != nil {
		return err
	}

	return nil
}

func (m *Propagate) validateByConsumer(formats strfmt.Registry) error {

	if err := validate.Required("by_consumer", "body", m.ByConsumer); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Propagate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Propagate) UnmarshalBinary(b []byte) error {
	var res Propagate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
