// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RemoveProducerRequest RemoveProducerRequest
// swagger:model RemoveProducerRequest
type RemoveProducerRequest struct {

	// resource ids
	// Required: true
	ResourceIds []string `json:"resource_ids"`
}

// Validate validates this remove producer request
func (m *RemoveProducerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemoveProducerRequest) validateResourceIds(formats strfmt.Registry) error {

	if err := validate.Required("resource_ids", "body", m.ResourceIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RemoveProducerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoveProducerRequest) UnmarshalBinary(b []byte) error {
	var res RemoveProducerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
